name: Criar PR Develop para Main

on:
  workflow_dispatch:

jobs:
  aviso:
    runs-on: ubuntu-latest
    steps:
      - name: Log Informativo
        run: echo "Este workflow foi substituído pelo auto-merge direto."
